// eslint-disable-next-line import/no-extraneous-dependencies
import { defineConfig } from 'cypress';

// eslint-disable-next-line import/no-default-export
export default defineConfig({
  e2e: {
    // We've imported your old cypress plugins here.
    // You may want to clean this up later by importing these.
    setupNodeEvents(on, config) {
      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
      // @ts-ignore TS doesn't like this autogenerated require.
      // eslint-disable-next-line global-require, @typescript-eslint/no-var-requires
      return require('./cypress/plugins/index.js')(on, config);
    },
  },
});
