// This file is mostly copy-pasted from 'cypress.config.ts' since these config files are
// alternatives. This file will have  performance optimized options, like disabling video
// recording and map tiles.
import { defineConfig } from 'cypress';

// eslint-disable-next-line import/no-default-export
export default defineConfig({
  e2e: {
    // Update default file paths to strip `/cypress/` folder prefix
    supportFile: 'support/e2e.{js,jsx,ts,tsx}',
    specPattern: 'e2e/**/*.cy.{js,jsx,ts,tsx}',
    fixturesFolder: 'fixtures',
    screenshotsFolder: 'reports/screenshots',
    defaultCommandTimeout: 20000,
    viewportWidth: 1920,
    viewportHeight: 1080,
    requestTimeout: 20000,
    // We've imported your old cypress plugins here.
    // You may want to clean this up later by importing these.
    setupNodeEvents(on, config) {
      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
      // @ts-ignore TS doesn't like this autogenerated require.
      // eslint-disable-next-line global-require, @typescript-eslint/no-var-requires
      return require('./plugins/index.js')(on, config);
    },
    // Configurations for optimizing the performance
    video: false,
  },
  env: {
    // Configurations for optimizing the performance
    DISABLE_MAP_TILES: true,
  },
});
