import { Crypto } from '@peculiar/webcrypto';
import { defineConfig } from 'cypress';

// fix following error that occurs on CI:
// The error was thrown while executing your e2e.setupNodeEvents() function:
// `Error: crypto.getRandomValues() not supported. See https://github.com/uuidjs/uuid#getrandomvalues-not-supported`
// (this happens because we are using uuidjs in test-db-manager module and
// for some reason it fails cypress tests )
global.crypto = new Crypto();

// eslint-disable-next-line import/no-default-export
export default defineConfig({
  e2e: {
    // Update default file paths to strip `/cypress/` folder prefix
    supportFile: 'support/e2e.{js,jsx,ts,tsx}',
    specPattern: 'e2e/**/*.cy.{js,jsx,ts,tsx}',
    fixturesFolder: 'fixtures',
    screenshotsFolder: 'reports/screenshots',
    videosFolder: 'reports/videos',
    defaultCommandTimeout: 10000,
    viewportWidth: 1920,
    viewportHeight: 1080,
    // We've imported your old cypress plugins here.
    // You may want to clean this up later by importing these.
    setupNodeEvents(on, config) {
      // eslint-disable-next-line @typescript-eslint/ban-ts-comment
      // @ts-ignore TS doesn't like this autogenerated require.
      // eslint-disable-next-line global-require, @typescript-eslint/no-var-requires
      return require('./plugins/index.js')(on, config);
    },
  },
});
