export enum Tag {
  Smoke = '@smoke',
  Map = '@map',
  Terminals = '@terminals',
  Network = '@network',
  Stops = '@stops',
  StopRegistry = '@stopRegistry',
  StopAreas = '@stopAreas',
  Routes = '@routes',
  Lines = '@lines',
  Login = '@login',
  Timetables = '@timetables',
  HastusExport = '@hastusExport',
  HastusImport = '@hastusImport',
  Search = '@search',
}
