name: 'E2E Cypress tests'
description: 'Runs e2e tests'

runs:
  using: 'composite'
  steps:
    - name: Run Cypress tests in started environment
      run: |
        # Get current date as a postfix for individual runs
        CURRENT_DATE=$(date +%s)

        # Run tests using the e2e docker bundle's cypress container
        docker exec cypress \
          bash -c "yarn test:e2e"

        # Retrieve test results from docker container to the reports folder
        docker cp cypress-tests:/reports/. "${{ github.workspace }}/reports/${CURRENT_DATE}/" || echo "No reports"

        # Cleanup test container
        docker rm --force cypress-tests
