name: 'E2E Cypress tests'
description: 'Runs e2e tests'

runs:
  using: 'composite'
  steps:
    - name: Run tests using the e2e docker bundle's cypress container
      run: |
        docker exec cypress \
          bash -c "yarn test:e2e"
      shell: bash

    - name: Retrieve test reports from container
      # should be run even if the tests fail
      if: always()
      run: |
        docker cp cypress:/e2e/cypress/reports ${{ github.workspace }}/cypress/ || echo "No reports"
      shell: bash

    - name: Upload test reports as an artifact
      # should be run even if the tests fail
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: cypress-docker-reports
        path: |
          ${{ github.workspace }}/cypress/reports

    - name: Fail the job The job has failed
      # should fail the job if the tests fail
      if: ${{ failure() }}
      run: |
        echo "E2E tests failed! See reports in the workflow's artifacts"
        exit 1
      shell: bash
