name: 'E2E Cypress tests'
description: 'Runs e2e tests'
inputs:
  test-tags:
    description: Specify a string of tags for tests to be run in format '@smoke'. To specify multiple tags, use format '@routes @smoke'. To run all tests, set it to ''.
    required: false
    default: '@smoke'

runs:
  using: 'composite'
  steps:
    - name: Run all tests using the e2e docker bundle's cypress container
      if: inputs.test-tags == ''
      run: |
        docker exec cypress \
          bash -c "yarn test:e2e"
      shell: bash

    - name: Run tests that have the provided tags
      if: startsWith(inputs.test-tags, '@')
      run: |
        docker exec cypress \
          bash -c "yarn test:e2e --env grepTags='${{ inputs.test-tags }}'"
      shell: bash

    - name: Retrieve test reports from container
      # should be run even if the tests fail
      if: always()
      run: |
        docker cp cypress:/e2e/cypress/reports ${{ github.workspace }}/cypress/ || echo "No reports"
      shell: bash

    - name: Upload test reports as an artifact
      # should be run even if the tests fail
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cypress-docker-reports
        path: |
          ${{ github.workspace }}/cypress/reports

    - name: Fail the job
      # should fail the job if the tests fail
      if: ${{ failure() }}
      run: |
        echo "E2E tests failed! See reports in the workflow's artifacts"
        exit 1
      shell: bash
