services:
  jore4-ui:
    build:
      context: ".."

  jore4-hasura:
    # locking hasura image so that we can develop the UI against a static graphql API
    # Link to available jore4-hasura imags in Docker Hub:
    # https://hub.docker.com/r/hsldevcom/jore4-hasura/tags?page=1&ordering=last_updated
    # The :hsl-tag contains the desired version of hsl specific hasura.
    # Waiting for merging feature-branch to main in hasura-repo
    # Note: also update jore4-hasura-e2e in docker-compose.e2e when changing this.
    image: 'hsldevcom/jore4-hasura:hsl-main--20240829-37c0ab1e4468fe1effc9a12f687297d010f8332b'
    # Waiting for database to be ready to avoid startup delay due to hasura crashing at startup if db is offline
    # Note: this should only be done in development setups as Kubernetes does not allow waiting for services to be ready
    depends_on:
      jore4-testdb:
        condition: service_healthy
      jore4-tiamat:
        condition: service_healthy
    # Uncomment the lines below to direct timetables-api actions from Hasura
    # to a locally built timetables API running on localhost instead of the dockerized version.
    # extra_hosts:
    #   - "jore4-timetablesapi:host-gateway"

  jore4-mapmatching:
    # pinning map-matching API to compatible version
    image: "hsldevcom/jore4-map-matching:main--20240820-f3a4b33f20a3c3c409205b52c35e6a3cb909153e"

  jore4-hastus:
    # pinning hastus import-export-microservice version
    image: "hsldevcom/jore4-hastus:main--20240822-69e017532c5619810a540089f6ec306523e5ebb0"
    environment:
      # use the same Hasura URL that the UI uses to enable routing requests to correct Hasura instances
      # when running e2e tests locally
      HASURA_URL: "http://host.docker.internal:3300/api/graphql/v1/graphql"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  jore4-tiamat:
    # Pin tiamat to a compatible version.
    # Note: also update jore4-tiamat-e2e in docker-compose.e2e when changing this.
    image: "hsldevcom/jore4-tiamat:main--20240826-11c0e8c023b4ab7d1ec7adf7e762b19b467fd44a"

  jore4-timetablesapi:
    # Pin timetables api to a compatible version.
    # Note: also update jore4-timetablesapi-e2e in docker-compose.e2e when changing this.
    image: 'hsldevcom/jore4-timetables-api:main--20240806-224646a980735f1219a358b7971748c4b043199a'
