services:
  jore4-ui:
    build:
      context: ".."

  jore4-hasura:
    # locking hasura image so that we can develop the UI against a static graphql API
    # Link to available jore4-hasura imags in Docker Hub:
    # https://hub.docker.com/r/hsldevcom/jore4-hasura/tags?page=1&ordering=last_updated
    # The :hsl-tag contains the desired version of hsl specific hasura.
    # Waiting for merging feature-branch to main in hasura-repo
    # Note: also update jore4-hasura-e2e in docker-compose.e2e when changing this.
    image: 'hsldevcom/jore4-hasura:hsl-main--20250213-923dac0225f1151e55f688bf7614d0891cc0492f'
    # Waiting for database to be ready to avoid startup delay due to hasura crashing at startup if db is offline
    # Note: this should only be done in development setups as Kubernetes does not allow waiting for services to be ready
    depends_on:
      jore4-testdb:
        condition: service_healthy
      jore4-tiamat:
        condition: service_healthy
    # Uncomment the lines below to direct timetables-api actions from Hasura
    # to a locally built timetables API running on localhost instead of the dockerized version.
    # extra_hosts:
    #   - "jore4-timetablesapi:host-gateway"

  jore4-mapmatching:
    # pinning map-matching API to compatible version
    image: "hsldevcom/jore4-map-matching:main--20240905-b35697db3217e9d33792c1518d0741c9a2babcd7"

  jore4-hastus:
    # pinning hastus import-export-microservice version
    image: "hsldevcom/jore4-hastus:main--20240906-7d2024adb1008dec08768b54a5ad73a74bd3d7fe"
    environment:
      # use the same Hasura URL that the UI uses to enable routing requests to correct Hasura instances
      # when running e2e tests locally
      HASURA_URL: "http://host.docker.internal:3300/api/graphql/v1/graphql"

  jore4-tiamat:
    # Pin tiamat to a compatible version.
    # Note: also update jore4-tiamat-e2e in docker-compose.e2e when changing this.
    image: "hsldevcom/jore4-tiamat:main--20250210-d1ec37d13530558e8a22aa51d7091614863a7ada"

  jore4-timetablesapi:
    # Pin timetables api to a compatible version.
    # Note: also update jore4-timetablesapi-e2e in docker-compose.e2e when changing this.
    image: 'hsldevcom/jore4-timetables-api:main--20240905-da293a99ddeff4776bc7c20d675832b0a407fe9f'
