services:
  jore4-hasura:
    # Temporarily overwrite the hasura version of the flux docker-compose bundle
    # because it did not contain the necessary migrations as of 14.10.2021.
    # However this section should be deleted after we have hasura updated in the bundle
    image: 'hsldevcom/jore4-hasura:main--e04e05996bf41fe7b3e75942f865b1f321e411b9'
    secrets:
      - source: db-jore3importer-username
        target: /mnt/secrets-store/db-jore3importer-username
    environment:
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'

  martin:
    image: urbica/martin
    restart: unless-stopped
    ports:
      - 3100:3000
    environment:
      - WATCH_MODE=true
      - DATABASE_URL=postgres://postgres:password@postgis/db
    depends_on:
      - postgis
    networks:
      - jore4

  postgis:
    # Try to match postgis used in Azure to avoid compatability
    # issues. See which version azure currently supports from documentation:
    # https://docs.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-extensions
    image: 'postgis/postgis:12-3.0-alpine'
    restart: 'unless-stopped'
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - 25432:5432
    networks:
      - jore4

secrets:
  db-jore3importer-username:
    file: ./secret-testdb-db-jore3importer-username
