services:
  jore4-hasura:
    # locking hasura image so that we can develop the UI against a static graphql API
    # Link to available jore4-hasura images in Docker Hub:
    # https://hub.docker.com/r/hsldevcom/jore4-hasura/tags?page=1&ordering=last_updated
    image: 'hsldevcom/jore4-hasura:seed-seed-extra-stop--20220224-9729cff535929326381a03ae18ba479372ff62d3'
    environment:
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'

  jore4-mapmatching:
    # pinning map-maching API to compatible version
    image: "hsldevcom/jore4-map-matching:main--c88198562a3800b412647f2e487f89ba5972f216"

  martin:
    image: urbica/martin
    restart: unless-stopped
    ports:
      - 3100:3000
    environment:
      - WATCH_MODE=true
      - DATABASE_URL=postgres://postgres:password@postgis/db
    depends_on:
      - postgis
    networks:
      - jore4

  postgis:
    # Try to match postgis used in Azure to avoid compatability
    # issues. See which version azure currently supports from documentation:
    # https://docs.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-extensions
    image: 'postgis/postgis:12-3.0-alpine'
    restart: 'unless-stopped'
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - 25432:5432
    networks:
      - jore4
