services:
  jore4-hasura:
    # locking hasura image so that we can develop the UI against a static graphql API
    image: 'hsldevcom/jore4-hasura:main--e4f5c5ad2dd1530207300c2d487de70fccb70431'
    environment:
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
    volumes:
      - './2524600800000_seed-data:/hasura-migrations/default/2524600800000_seed-data'

  martin:
    image: urbica/martin
    restart: unless-stopped
    ports:
      - 3100:3000
    environment:
      - WATCH_MODE=true
      - DATABASE_URL=postgres://postgres:password@postgis/db
    depends_on:
      - postgis
    networks:
      - jore4

  postgis:
    # Try to match postgis used in Azure to avoid compatability
    # issues. See which version azure currently supports from documentation:
    # https://docs.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-extensions
    image: 'postgis/postgis:12-3.0-alpine'
    restart: 'unless-stopped'
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - 25432:5432
    networks:
      - jore4

  jore4-testdb:
    # preserve db's state to local disk to avoid data loss if db container is removed
    volumes:
      - './testdb:/var/lib/postgresql/data'
