query GetStopWithRouteGraphDataById($stopId: uuid!) {
  service_pattern_scheduled_stop_point(
    where: { scheduled_stop_point_id: { _eq: $stopId } }
  ) {
    ...ScheduledStopPointAllFields

    scheduled_stop_point_in_journey_patterns {
      ...ScheduledStopPointInJourneyPatternAllFields

      journey_pattern {
        journey_pattern_id

        journey_pattern_route {
          ...RouteDefaultFields

          infrastructure_links_along_route {
            route_id
            infrastructure_link_id
            infrastructure_link_sequence
          }
        }
      }
    }
  }
}
