fragment RouteValidity on route_route {
  validity_start
  validity_end
  priority
}

fragment RouteUniqueFields on route_route {
  ...RouteValidity
  label
  direction
  variant
  route_id
}

fragment RouteDefaultFields on route_route {
  ...RouteUniqueFields
  name_i18n
  description_i18n
  version_comment
  origin_name_i18n
  origin_short_name_i18n
  destination_name_i18n
  destination_short_name_i18n
  on_line_id
}

fragment RouteAllFields on route_route {
  ...RouteDefaultFields
  route_shape
}

fragment RouteWithJourneyPatternStops on route_route {
  ...RouteAllFields

  route_journey_patterns {
    journey_pattern_id
    on_route_id

    ordered_scheduled_stop_point_in_journey_patterns: scheduled_stop_point_in_journey_patterns(
      order_by: { scheduled_stop_point_sequence: asc }
    ) {
      ...ScheduledStopPointInJourneyPatternAllFields

      scheduled_stop_points {
        ...ScheduledStopPointDefaultFields
      }
    }
  }
}

fragment RouteWithInfrastructureLinks on route_route {
  ...RouteAllFields

  route_line {
    ...LineAllFields
  }

  infrastructure_links_along_route {
    route_id
    infrastructure_link_sequence
    infrastructure_link_id
    infrastructure_link {
      infrastructure_link_id
      shape
      direction
      external_link_id
      external_link_source
    }
    is_traversal_forwards
  }
}
