fragment route_validity on route_route {
  validity_start
  validity_end
  priority
}

fragment route_unique_fields on route_route {
  ...route_validity
  label
  direction
  variant
  route_id
}

fragment route_default_fields on route_route {
  ...route_unique_fields
  name_i18n
  description_i18n
  version_comment
  origin_name_i18n
  origin_short_name_i18n
  destination_name_i18n
  destination_short_name_i18n
  on_line_id
}

fragment route_all_fields on route_route {
  ...route_default_fields
  route_shape
}

fragment route_with_journey_pattern_stops on route_route {
  ...route_all_fields

  route_journey_patterns {
    journey_pattern_id
    on_route_id

    ordered_scheduled_stop_point_in_journey_patterns: scheduled_stop_point_in_journey_patterns(
      order_by: { scheduled_stop_point_sequence: asc }
    ) {
      ...scheduled_stop_point_in_journey_pattern_all_fields

      scheduled_stop_points {
        ...scheduled_stop_point_default_fields
      }
    }
  }
}

fragment route_with_infrastructure_links on route_route {
  ...route_all_fields

  route_line {
    ...line_all_fields
  }

  infrastructure_links_along_route {
    route_id
    infrastructure_link_sequence
    infrastructure_link_id
    infrastructure_link {
      infrastructure_link_id
      shape
      direction
      external_link_id
      external_link_source
    }
    is_traversal_forwards
  }
}
