fragment ScheduledStopPointDefaultFields on service_pattern_scheduled_stop_point {
  priority
  direction
  scheduled_stop_point_id
  label
  timing_place_id
  timing_place {
    timing_place_id
    label
  }
  validity_start
  validity_end
  located_on_infrastructure_link_id
  stop_place_ref
}

fragment ScheduledStopPointAllFields on service_pattern_scheduled_stop_point {
  ...ScheduledStopPointDefaultFields

  measured_location
  relative_distance_from_infrastructure_link_start
  closest_point_on_infrastructure_link
  vehicle_mode_on_scheduled_stop_point {
    vehicle_mode
  }
}

fragment StopWithJourneyPatternFields on service_pattern_scheduled_stop_point {
  ...ScheduledStopPointAllFields

  scheduled_stop_point_in_journey_patterns {
    ...ScheduledStopPointInJourneyPatternAllFields
  }
}

fragment RouteStopFields on service_pattern_scheduled_stop_point {
  ...StopWithJourneyPatternFields

  stop_place {
    id
    version
    name {
      lang
      value
    }
  }

  other_label_instances {
    ...ScheduledStopPointDefaultFields
  }
}
