name: Run cypress tests

on:
  # this workflow is only called by others, won't be executed on itself
  # as it uses the pre-built docker image that is produced in the upstream job
  workflow_call:

jobs:
  run_cypress_tests:
    name: Run cypress e2e tests from docker
    runs-on: ubuntu-latest-4-cores
    env:
      CYPRESS_IMAGE_NAME: hsldevcom/jore4-cypress

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract metadata to env variables
        uses: HSLdevcom/jore4-tools/github-actions/extract-metadata@extract-metadata-v1

      - name: Start e2e env
        uses: HSLdevcom/jore4-tools/github-actions/setup-e2e-environment@setup-e2e-environment-v1
        with:
          ui_version: '${{ env.IMAGE_NAME }}:${{ env.COMMIT_ID }}'
          cypress_version: '${{ env.CYPRESS_IMAGE_NAME }}:${{ env.COMMIT_ID }}'

      - name: Set up PostgreSQL client
        run: |
          sudo apt-get -yqq install postgresql-client

      - name: Seed db1 with infrastructure links
        env:
          DUMP_PATH: ./test-db-manager/src/dumps/infraLinks/infraLinks.sql
        run: |
          psql postgresql://dbadmin:adminpassword@localhost:6532/jore4e2e < ${{ env.DUMP_PATH }}

      - name: Seed db2 with infrastructure links
        env:
          DUMP_PATH: ./test-db-manager/src/dumps/infraLinks/infraLinks.sql
        run: |
          psql postgresql://dbadmin:adminpassword@localhost:6533/jore4e2e < ${{ env.DUMP_PATH }}

      - name: Seed db3 with infrastructure links
        env:
          DUMP_PATH: ./test-db-manager/src/dumps/infraLinks/infraLinks.sql
        run: |
          psql postgresql://dbadmin:adminpassword@localhost:6534/jore4e2e < ${{ env.DUMP_PATH }}

      - name: Seed db4 with infrastructure links
        env:
          DUMP_PATH: ./test-db-manager/src/dumps/infraLinks/infraLinks.sql
        run: |
          psql postgresql://dbadmin:adminpassword@localhost:6432/jore4e2e < ${{ env.DUMP_PATH }}

      - name: Run e2e tests from github action
        id: run-e2e-tests
        uses: HSLdevcom/jore4-tools/github-actions/run-cypress-tests@run-cypress-tests-v1
        with:
          test-tags: ''
          video: 'false'
          threads: '3'
