name: Run cypress tests

on:
  # this workflow is only called by others, won't be executed on itself
  # as it uses the pre-built docker image that is produced in the upstream job
  workflow_call:

jobs:
  run_cypress_tests:
    name: Run cypress e2e tests from docker
    # These must run on ubuntu 22.04 or older.
    # The MS SQL server used by jore4-jore3-importer,
    # does not run on Linux kernels newer than 6.6.x.
    runs-on: ubuntu-22.04
    env:
      CYPRESS_IMAGE_NAME: hsldevcom/jore4-cypress

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Extract metadata to env variables
        uses: HSLdevcom/jore4-tools/github-actions/extract-metadata@extract-metadata-v1

      - name: Start e2e env
        uses: HSLdevcom/jore4-tools/github-actions/setup-e2e-environment@setup-e2e-environment-v6
        with:
          ui_version: '${{ env.IMAGE_NAME }}:${{ env.COMMIT_ID }}'
          cypress_version: '${{ env.CYPRESS_IMAGE_NAME }}:${{ env.COMMIT_ID }}'

      - name: Set up PostgreSQL client
        run: |
          sudo apt-get -yqq install postgresql-client

      - name: Seed db with infrastructure links
        env:
          DUMP_PATH: ./test-db-manager/src/dumps/infraLinks/infraLinks.sql
        run: |
          psql postgresql://dbadmin:adminpassword@localhost:6432/jore4e2e < ${{ env.DUMP_PATH }}

      - name: Seed Tiamat DB
        run: scripts/seed-municipalities-and-fare-zones.sh 3010

      - name: Run e2e tests from github action
        env:
          CYPRESS_TESTS_KEPT_IN_MEMORY: 0
        timeout-minutes: 15
        uses: HSLdevcom/jore4-tools/github-actions/run-cypress-tests@run-cypress-tests-v1
        with:
          test-tags: ''
