name: Run robot tests

on:
  # this workflow is only called by others, won't be executed on itself
  # as it uses the pre-built docker image that is produced in the upstream job
  workflow_call:
    secrets:
      ROBOT_HSLID_EMAIL:
        required: true
      ROBOT_HSLID_PASSWORD:
        required: true

jobs:
  run_e2e_tests_from_main:
    name: Run default jore4-robot e2e tests
    runs-on: ubuntu-20.04
    steps:
      - name: Extract metadata to env variables
        uses: HSLdevcom/jore4-tools/github-actions/extract-metadata@extract-metadata-v1

      - name: start e2e env
        uses: HSLdevcom/jore4-flux/github-actions/setup-e2e-environment@setup-e2e-environment-v1
        with:
          ui_version: $IMAGE_NAME:$COMMIT_ID

      - name: run e2e smoke tests
        id: tests
        uses: HSLdevcom/jore4-robot/github-actions/run-rf-tests@actions-v1
        with:
          included_tag: smoke
          e2e_username: ${{ secrets.ROBOT_HSLID_EMAIL }}
          e2e_password: ${{ secrets.ROBOT_HSLID_PASSWORD }}

      - name: upload test results
        if: always()
        uses: HSLdevcom/jore4-robot/github-actions/upload-results@actions-v1

  run_e2e_tests_from_branch:
    name: Run e2e tests from jore4-robot branch
    runs-on: ubuntu-20.04
    steps:
      - name: Extract metadata to env variables
        uses: HSLdevcom/jore4-tools/github-actions/extract-metadata@extract-metadata-v1

      - name: start e2e env
        uses: HSLdevcom/jore4-flux/github-actions/setup-e2e-environment@setup-e2e-environment-v1
        with:
          ui_version: $IMAGE_NAME:$COMMIT_ID

      - name: check if branch exists in e2e test repo
        run: |
          export BRANCH_EXISTS=$(git ls-remote --exit-code --heads https://github.com/HSLdevcom/jore4-robot.git ${{ env.BRANCH_NAME }})
          if [ -n "$BRANCH_EXISTS" ]; then
            echo "Branch found in E2E test repository!"
          else
            echo "Branch not found in E2E test repository!"
          fi
          echo "BRANCH_EXISTS=${BRANCH_EXISTS}" >> "${GITHUB_ENV}"

      - name: run e2e smoke tests from branch
        if: ${{ env.BRANCH_EXISTS }}
        uses: HSLdevcom/jore4-robot/github-actions/run-rf-tests@actions-v1
        with:
          included_tag: smoke
          test_suite_version: ${{ env.BRANCH_NAME }}
          e2e_username: ${{ secrets.ROBOT_HSLID_EMAIL }}
          e2e_password: ${{ secrets.ROBOT_HSLID_PASSWORD }}

      - name: upload test results
        if: ${{ always() && env.BRANCH_EXISTS }}
        uses: HSLdevcom/jore4-robot/github-actions/upload-results@actions-v1
