name: Run cypress tests

on:
  # this workflow is only called by others, won't be executed on itself
  # as it uses the pre-built docker image that is produced in the upstream job
  workflow_call:

jobs:
  run_cypress_tests:
    name: Run cypress e2e tests from docker
    runs-on: ubuntu-20.04
    env:
      CYPRESS_IMAGE_NAME: hsldevcom/jore4-cypress

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract metadata to env variables
        uses: HSLdevcom/jore4-tools/github-actions/extract-metadata@extract-metadata-v1

      - name: start e2e env
        uses: HSLdevcom/jore4-flux/github-actions/setup-e2e-environment@setup-e2e-environment-v1
        with:
          ui_version: $IMAGE_NAME:$COMMIT_ID

      - name: Verify that all services are up and running
        uses: HSLdevcom/jore4-tools/github-actions/healthcheck@healthcheck-v1
        with:
          command: '[ -z "$(docker ps -q --filter health=unhealthy --filter health=starting)" ]'

      - name: Run the the docker image containing the cypress tests
        run: |
          # pin the just-built version of the cypress image
          export CYPRESS_DOCKER_IMAGE="$CYPRESS_IMAGE_NAME:$COMMIT_ID"

          # run the e2e tests from the docker image
          # note: need to explicitly name the container here to be able to reference it later
          docker-compose -f ./docker/docker-compose.cypress.yml run --name cypress jore4-cypress yarn test:e2e

      - name: Retrieve test reports from container
        if: always()
        run: |
          docker cp cypress:/e2e/cypress/reports ${{ github.workspace }}/cypress/ || echo "No reports"

      - name: Upload test reports as an artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-docker-reports
          path: |
            ${{ github.workspace }}/cypress/reports
