name: Run cypress tests

on:
  # This workflow is only called by others, won't be executed on itself
  # as it uses the pre-built Docker image that is produced in the upstream job.
  workflow_call:

jobs:
  run_cypress_tests:
    name: Run cypress e2e tests from docker
    runs-on: ubuntu-24.04
    env:
      CYPRESS_IMAGE_NAME: hsldevcom/jore4-cypress

    steps:
      - name: Extract metadata to env variables
        uses: HSLdevcom/jore4-tools/github-actions/extract-metadata@extract-metadata-v1

      - name: Setup environment and run e2e tests from GitHub action
        uses: HSLdevcom/jore4-tools/github-actions/run-ci@main
        with:
          ui_version: '${{ env.IMAGE_NAME }}:${{ env.COMMIT_ID }}'
          cypress_version: '${{ env.CYPRESS_IMAGE_NAME }}:${{ env.COMMIT_ID }}'
          tiamat_version: 'hsldevcom/jore4-tiamat:stop-place-name-check--20250304-5bf44544646bfda168727ba5647fd36abdb3d2f7'
          hasura_version: 'hsldevcom/jore4-hasura:hsl-feature-48598-Link_scheduled_stop_point_to_quay_--20250213-2947673ba807f1177716fc1d181a69ad6699175b'
          test-tags: ''
